name: 'quarto-rsync'
description: 'Create docs with nbdev'
inputs:
  username:
    description: 'rsync user'
    required: true
  hostname:
    description: 'rsync host'
    required: true
  dest_path:
    description: 'path to rsync to'
    required: true
  ssh_key:
    description: "SSH key for rsync"
    required: true
  delete:
    description: "Toggle the --delete flag on or off for rsync.  Set to any value to enable.  Disabled by default."
    required: false
    default: ''
  pre:
    description: 'Install prerelease nbdev/execnb from master?'
    required: false
    default: ''
  torch_cpu:
    description: "Install PyTorch CPU instead of PyTorch Cuda.  Has no effect if PyTorch isn't a requirement.  Enabled by defaut."
    required: false
    default: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
    - name: Install deps, build docs, and sync
      env:
        SSH_KEY: ${{ inputs.ssh_key }}
        USE_PRE: ${{ inputs.pre }}
        delete: "${{ inputs.delete }}"
        TORCH_CPU: "${{ inputs.torch_cpu }}"
      run: |
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh
        echo "$SSH_KEY" > ~/.ssh/id_rsa
        echo -e 'Host *\n  StrictHostKeyChecking no' > ~/.ssh/config
        chmod 600 ~/.ssh/*
        python -m pip install --upgrade pip
        if [ $USE_PRE ]; then
          pip install -U git+https://github.com/fastai/fastcore.git
          pip install -U git+https://github.com/fastai/execnb.git
          pip install -U git+https://github.com/fastai/nbdev.git
        else
          pip install -U nbdev
        fi
        if [ $TORCH_CPU ]; then
          pip install -e ".[dev]" --extra-index-url https://download.pytorch.org/whl/cpu
        else
          pip install -e ".[dev]"
        fi
        nbdev_docs
        rsync $(echo ${delete:+'--delete'}) -az _docs/ ${{ inputs.username }}@${{ inputs.hostname }}:${{ inputs.dest_path }}/
      shell: bash

